name: cripstory
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state management
  provider: ^6.0.5

  #navigation managment
  go_router: ^11.0.0

  #requests to API
  http: ^1.1.0

  #graphics
  fl_chart: ^0.63.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
